---

#Select the hosts you wish to use
- hosts: all
#  Facts requires Python to be installed on the host machine and get info about the machine. This is set to true by default and could crash the machine
  gather_facts: False
#  This is required if the username is set on the remote user (needs to match) 
  remote_user: ubuntu
#When become is set the user will change to what is entered
  become: yes
#This will become the root user
  become_user: root
#Escalates the user level to root 
  become_method: sudo

   
#Tasks start with a name and '-' (indentation matters). The name is just a description and raw is the actual task. '||' means OR, so if the below statement fails then it will install python 

  tasks:

  - name: Install Python 2
    raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python)
  
 #This will locate and use the public key as authorised 
  - name: Authorized keys
    authorized_key: user=ubuntu
                    exclusive=no
                    key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
